cc_binary(
    name = "user_client",
    srcs = ["user_client.cpp",
            "user_client.hpp",
            "user.grpc.pb.cc",
            "user.pb.cc",
            "user.grpc.pb.h",
            "user.pb.h"],
    deps = ["@com_github_grpc_grpc//:grpc++", "@com_github_grpc_grpc//:grpc_plugin_support"]
)

