// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user.proto

#include "user.pb.h"
#include "user.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace user {

static const char* User_method_names[] = {
  "/user.User/SignUp",
  "/user.User/SignIn",
};

std::unique_ptr< User::Stub> User::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< User::Stub> stub(new User::Stub(channel));
  return stub;
}

User::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SignUp_(User_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SignIn_(User_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status User::Stub::SignUp(::grpc::ClientContext* context, const ::user::UserRequest& request, ::user::UserReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SignUp_, context, request, response);
}

void User::Stub::experimental_async::SignUp(::grpc::ClientContext* context, const ::user::UserRequest* request, ::user::UserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SignUp_, context, request, response, std::move(f));
}

void User::Stub::experimental_async::SignUp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::user::UserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SignUp_, context, request, response, std::move(f));
}

void User::Stub::experimental_async::SignUp(::grpc::ClientContext* context, const ::user::UserRequest* request, ::user::UserReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SignUp_, context, request, response, reactor);
}

void User::Stub::experimental_async::SignUp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::user::UserReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SignUp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::UserReply>* User::Stub::AsyncSignUpRaw(::grpc::ClientContext* context, const ::user::UserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::user::UserReply>::Create(channel_.get(), cq, rpcmethod_SignUp_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::user::UserReply>* User::Stub::PrepareAsyncSignUpRaw(::grpc::ClientContext* context, const ::user::UserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::user::UserReply>::Create(channel_.get(), cq, rpcmethod_SignUp_, context, request, false);
}

::grpc::Status User::Stub::SignIn(::grpc::ClientContext* context, const ::user::UserRequest& request, ::user::UserReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SignIn_, context, request, response);
}

void User::Stub::experimental_async::SignIn(::grpc::ClientContext* context, const ::user::UserRequest* request, ::user::UserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SignIn_, context, request, response, std::move(f));
}

void User::Stub::experimental_async::SignIn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::user::UserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SignIn_, context, request, response, std::move(f));
}

void User::Stub::experimental_async::SignIn(::grpc::ClientContext* context, const ::user::UserRequest* request, ::user::UserReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SignIn_, context, request, response, reactor);
}

void User::Stub::experimental_async::SignIn(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::user::UserReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SignIn_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::UserReply>* User::Stub::AsyncSignInRaw(::grpc::ClientContext* context, const ::user::UserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::user::UserReply>::Create(channel_.get(), cq, rpcmethod_SignIn_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::user::UserReply>* User::Stub::PrepareAsyncSignInRaw(::grpc::ClientContext* context, const ::user::UserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::user::UserReply>::Create(channel_.get(), cq, rpcmethod_SignIn_, context, request, false);
}

User::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      User_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< User::Service, ::user::UserRequest, ::user::UserReply>(
          std::mem_fn(&User::Service::SignUp), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      User_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< User::Service, ::user::UserRequest, ::user::UserReply>(
          std::mem_fn(&User::Service::SignIn), this)));
}

User::Service::~Service() {
}

::grpc::Status User::Service::SignUp(::grpc::ServerContext* context, const ::user::UserRequest* request, ::user::UserReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status User::Service::SignIn(::grpc::ServerContext* context, const ::user::UserRequest* request, ::user::UserReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace user

